# Learn Python From Zero For Absolute Beginner (1): Data Cleaning

Welcome to our first lesson of the "Learn Python From Zero For Absolute Beginner" series!

Here, you'll find the completed full code for the task at hand. However, if you're looking for a more detailed understanding and want to **follow along step by step with thorough explanations**, we highly recommend you to read our article below:

 👉 https://digitalhumanities.hkust.edu.hk/tutorials/learn-python-from-zero-for-absolute-beginner-1-data-cleaning/

The article provides comprehensive explanations and instructions that will help you grasp the underlying concepts.


---

## Install Python libraries

### Method 1

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

### Method 2

In [ ]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

---

## Import Python libraries

In [ ]:
import pandas as pd

---


## Import data from Excel

Click [here](https://bit.ly/hkust-dh-github-data-threadbound) to download the Excel file `data_dh-tutorial_rse-ChiBksBefore1949-ThreadBound.xlsx` and upload it to your Google Drive.

In [ ]:
# Change the filepath according to your file location
filepath = '/content/drive/MyDrive/Colab Notebooks/data/data_dh-tutorial_rse-ChiBksBefore1949-ThreadBound.xlsx'

In [ ]:
data = pd.read_excel(filepath, sheet_name='rawdata')

In [ ]:
# preview
data

    Year published
0          1600(1)
1          1655(1)
2          1705(1)
3          1709(1)
4          1748(1)
..             ...
101       1945(10)
102        1946(4)
103        1947(5)
104        1948(6)
105        1949(3)

[106 rows x 1 columns]

In [ ]:
# preview the first few rows (default as 5)
data.head()

  Year published
0        1600(1)
1        1655(1)
2        1705(1)
3        1709(1)
4        1748(1)

In [ ]:
# preview the first 8 rows
data.head(8)

  Year published
0        1600(1)
1        1655(1)
2        1705(1)
3        1709(1)
4        1748(1)
5        1749(1)
6        1781(1)
7        1786(1)

In [ ]:
# preview the last few rows (default as 5)
data.tail()

    Year published
101       1945(10)
102        1946(4)
103        1947(5)
104        1948(6)
105        1949(3)

---

## Data cleaning

### Split one column to multiple columns according to special character

In [ ]:
data[['year','number of items']] = data['Year published'].str.split('(',expand=True)

In [ ]:
# preview
data.head()

  Year published  year number of items
0        1600(1)  1600              1)
1        1655(1)  1655              1)
2        1705(1)  1705              1)
3        1709(1)  1709              1)
4        1748(1)  1748              1)

---

### Remove columns

In [ ]:
data = data.drop(columns=['Year published'])

In [ ]:
# preview
data.head()

   year number of items
0  1600              1)
1  1655              1)
2  1705              1)
3  1709              1)
4  1748              1)

---

### Replace specific character

In [ ]:
data['number of items'] = data['number of items'].str.replace(')','')

<ipython-input-14-4077daa5068f>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['number of items'] = data['number of items'].str.replace(')','')

In [ ]:
# preview
data.head()

   year number of items
0  1600               1
1  1655               1
2  1705               1
3  1709               1
4  1748               1

---

### Check whether there is missing value

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             106 non-null    object
 1   number of items  106 non-null    object
dtypes: object(2)
memory usage: 1.8+ KB

### Change the data type of the column

In [ ]:
data['number of items'] = data['number of items'].astype('int')
data['year'] = data['year'].astype('int')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             106 non-null    int64
 1   number of items  106 non-null    int64
dtypes: int64(2)
memory usage: 1.8 KB

---

### Descriptive statistics (get max and min values)

In [ ]:
data.describe()

              year  number of items
count   106.000000       106.000000
mean   1880.386792         6.377358
std      61.890313         9.737950
min    1600.000000         1.000000
25%    1854.750000         1.000000
50%    1895.500000         3.000000
75%    1922.750000         7.000000
max    1949.000000        56.000000

In [ ]:
data.describe().round(1)

         year  number of items
count   106.0            106.0
mean   1880.4              6.4
std      61.9              9.7
min    1600.0              1.0
25%    1854.8              1.0
50%    1895.5              3.0
75%    1922.8              7.0
max    1949.0             56.0

### Get the row of maximum value (loc, idxmax)

In [ ]:
yearMaxItems = data.loc[data['number of items'].idxmax()]

Let's break down the code and understand its functionality:

In [ ]:
print(data['number of items'].idxmax())

42

In [ ]:
print(data.loc[42])

year               1884
number of items      56
Name: 42, dtype: int64

In [ ]:
yearMaxItems

year               1884
number of items      56
Name: 42, dtype: int64

In [ ]:
print(yearMaxItems[0])

1884

In [ ]:
print(yearMaxItems[1])

56

---

### Concatenation (combine string and variables)

In [ ]:
print(data['number of items'].sum())

676

In [ ]:
sumvalue = data['number of items'].sum()

In [ ]:
print('There are a total of ', sumvalue, ' items in this collection.')

There are a total of  676  items in this collection.

In [ ]:
print('There are a total of ' + str(sumvalue) + ' items in this collection.')

There are a total of 676 items in this collection.

In [ ]:
print(f'There are a total of {sumvalue} items in this collection.')

There are a total of 676 items in this collection.

In [ ]:
print(f'Maximum: In this collection, there are {yearMaxItems[1]} items that were published in {yearMaxItems[0]}.')

Maximum: In this collection, there are 56 items that were published in 1884.

---

### Assign labels to new column according to conditions (for loops, if...else)

#### Method 1

Create a function, use `for` loop and `if...elif...else` statement

In [ ]:
# create a function called "grouped_year"
def grouped_year(year):
  if 1501 <= year <= 1600:     # if the value of year is larger than or equal to 1501 AND smaller than or equal to 1600
    return "16th century"      # then, assign "16th century" to the "Period" column for this row
  elif 1601 <= year <= 1700:
    return "17th century"
  elif 1701 <= year <= 1800:
    return "18th century"
  elif 1801 <= year <= 1900:
    return "19th century"
  elif 1901 <= year <= 2000:
    return "20th century"
  else:
    return "Ungrouped"         # in case any values fall outside the above scope, show "Ungrouped" in the "Period" column for this row

In [ ]:
# make a copy of the original dataframe "data", and named the copy as "data1"
data1 = data.copy()

In [ ]:
data1["Period"] = data["year"].apply(lambda year: grouped_year(year))

In [ ]:
# preview
data1

     year  number of items        Period
0    1600                1  16th century
1    1655                1  17th century
2    1705                1  18th century
3    1709                1  18th century
4    1748                1  18th century
..    ...              ...           ...
101  1945               10  20th century
102  1946                4  20th century
103  1947                5  20th century
104  1948                6  20th century
105  1949                3  20th century

[106 rows x 3 columns]

In [ ]:
# the "data" dataframe will not be affected
data

     year  number of items
0    1600                1
1    1655                1
2    1705                1
3    1709                1
4    1748                1
..    ...              ...
101  1945               10
102  1946                4
103  1947                5
104  1948                6
105  1949                3

[106 rows x 2 columns]

#### Method 2

Use 1 line of code

In [ ]:
# make a copy of the original dataframe "data", and named the copy as "data2"
data2 = data.copy()

In [ ]:
data2['Period'] = ['16th century' if 1501 <= year <= 1600 else '17th century' if 1601 <= year <= 1700 else '18th century' if 1701 <= year <= 1800 else '19th century' if 1801 <= year <= 1900 else '20th century' if 1901 <= year <= 2000 else "Ungrouped" for year in data['year']]

In [ ]:
# preview
data2

     year  number of items        Period
0    1600                1  16th century
1    1655                1  17th century
2    1705                1  18th century
3    1709                1  18th century
4    1748                1  18th century
..    ...              ...           ...
101  1945               10  20th century
102  1946                4  20th century
103  1947                5  20th century
104  1948                6  20th century
105  1949                3  20th century

[106 rows x 3 columns]

In [ ]:
# the "data" dataframe will not be affected
data

     year  number of items
0    1600                1
1    1655                1
2    1705                1
3    1709                1
4    1748                1
..    ...              ...
101  1945               10
102  1946                4
103  1947                5
104  1948                6
105  1949                3

[106 rows x 2 columns]

---

### Group data (similar to pivot table in Excel)

In [ ]:
# make a copy of the dataframe "data2", and named the copy as "data_r1"
data_r1 = data2.copy()

In [ ]:
# find the number of distinct year in each period
data_r1 = data_r1.groupby('Period')['year'].count().reset_index()

# rename the column "year" to "distinct year"
data_r1.rename(columns={'year':'distinct year'}, inplace=True)

In [ ]:
# preview
data_r1

         Period  distinct year
0  16th century              1
1  17th century              1
2  18th century              8
3  19th century             48
4  20th century             48

In [ ]:
# make a copy of the dataframe "data2", and named the copy as "data_r2"
data_r2 = data2.copy()

In [ ]:
# find the sum of number of items in each period
data_r2 = data_r2.groupby('Period')['number of items'].sum().reset_index()

In [ ]:
# preview
data_r2

         Period  number of items
0  16th century                1
1  17th century                1
2  18th century                8
3  19th century              218
4  20th century              448

---

### Merge two tables/dataframes

In [ ]:
# Merge two DataFrame based on a particular column
data_r_merge = pd.merge(data_r1, data_r2, on='Period')

In [ ]:
# preview
data_r_merge

         Period  distinct year  number of items
0  16th century              1                1
1  17th century              1                1
2  18th century              8                8
3  19th century             48              218
4  20th century             48              448

# Next article: Data Visualization

Moving forward, we invite you to join us in our next article, where we will embark on the journey into the realm of data visualization. Together, we will explore the powerful capabilities of Python for creating interactive charts and graphs. These visualizations will enable you to gain deeper insights into your data.

👉 https://digitalhumanities.hkust.edu.hk/tutorials/learn-python-from-zero-for-absolute-beginner-2-data-visualization/